from google.cloud import bigquery

DEPUTES_SCHEMAS: dict[str, list[bigquery.SchemaField]] = {
    "acteurs": [
        bigquery.SchemaField("uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("civilite", "STRING"),
        bigquery.SchemaField("prenom", "STRING"),
        bigquery.SchemaField("nom", "STRING"),
        bigquery.SchemaField("alpha", "STRING"),
        bigquery.SchemaField("trigramme", "STRING"),
        bigquery.SchemaField("date_naissance", "DATE"),
        bigquery.SchemaField("ville_naissance", "STRING"),
        bigquery.SchemaField("departement_naissance", "STRING"),
        bigquery.SchemaField("pays_naissance", "STRING"),
        bigquery.SchemaField("profession_libelle", "STRING"),
        bigquery.SchemaField("profession_categorie", "STRING"),
        bigquery.SchemaField("profession_famille", "STRING"),
        bigquery.SchemaField("uri_hatvp", "STRING"),
        bigquery.SchemaField("ingested_at", "TIMESTAMP", mode="REQUIRED"),
    ],
    "adresses": [
        bigquery.SchemaField("uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("acteur_uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("type_code", "STRING"),
        bigquery.SchemaField("type_libelle", "STRING"),
        bigquery.SchemaField("xsi_type", "STRING"),
        bigquery.SchemaField("intitule", "STRING"),
        bigquery.SchemaField("numero_rue", "STRING"),
        bigquery.SchemaField("nom_rue", "STRING"),
        bigquery.SchemaField("complement", "STRING"),
        bigquery.SchemaField("code_postal", "STRING"),
        bigquery.SchemaField("ville", "STRING"),
        bigquery.SchemaField("val_elec", "STRING"),
        bigquery.SchemaField("ingested_at", "TIMESTAMP", mode="REQUIRED"),
    ],
    "mandats": [
        bigquery.SchemaField("uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("acteur_ref", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("xsi_type", "STRING"),
        bigquery.SchemaField("legislature", "STRING"),
        bigquery.SchemaField("type_organe", "STRING"),
        bigquery.SchemaField("organe_ref", "STRING"),
        bigquery.SchemaField("date_debut", "DATE"),
        bigquery.SchemaField("date_fin", "DATE"),
        bigquery.SchemaField("date_publication", "DATE"),
        bigquery.SchemaField("preseance", "INTEGER"),
        bigquery.SchemaField("nomin_principale", "BOOLEAN"),
        bigquery.SchemaField("code_qualite", "STRING"),
        bigquery.SchemaField("lib_qualite", "STRING"),
        bigquery.SchemaField("election_departement", "STRING"),
        bigquery.SchemaField("election_num_departement", "STRING"),
        bigquery.SchemaField("election_num_circo", "STRING"),
        bigquery.SchemaField("election_cause_mandat", "STRING"),
        bigquery.SchemaField("mandature_date_prise_fonction", "DATE"),
        bigquery.SchemaField("mandature_cause_fin", "STRING"),
        bigquery.SchemaField("mandature_premiere_election", "BOOLEAN"),
        bigquery.SchemaField("mandature_place_hemicycle", "INTEGER"),
        bigquery.SchemaField("ingested_at", "TIMESTAMP", mode="REQUIRED"),
    ],
    "organes": [
        bigquery.SchemaField("uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("xsi_type", "STRING"),
        bigquery.SchemaField("code_type", "STRING"),
        bigquery.SchemaField("libelle", "STRING"),
        bigquery.SchemaField("libelle_abrege", "STRING"),
        bigquery.SchemaField("libelle_abrev", "STRING"),
        bigquery.SchemaField("regime", "STRING"),
        bigquery.SchemaField("legislature", "STRING"),
        bigquery.SchemaField("date_debut", "DATE"),
        bigquery.SchemaField("date_fin", "DATE"),
        bigquery.SchemaField("circo_numero", "STRING"),
        bigquery.SchemaField("circo_region_type", "STRING"),
        bigquery.SchemaField("circo_region_libelle", "STRING"),
        bigquery.SchemaField("circo_dep_code", "STRING"),
        bigquery.SchemaField("circo_dep_libelle", "STRING"),
        bigquery.SchemaField("gp_couleur", "STRING"),
        bigquery.SchemaField("gp_preseance", "INTEGER"),
        bigquery.SchemaField("gp_position_politique", "STRING"),
        bigquery.SchemaField("ingested_at", "TIMESTAMP", mode="REQUIRED"),
    ],
    "deports": [
        bigquery.SchemaField("uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("legislature", "STRING"),
        bigquery.SchemaField("acteur_ref", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("date_creation", "TIMESTAMP"),
        bigquery.SchemaField("date_publication", "TIMESTAMP"),
        bigquery.SchemaField("portee_code", "STRING"),
        bigquery.SchemaField("portee_libelle", "STRING"),
        bigquery.SchemaField("lecture_code", "STRING"),
        bigquery.SchemaField("instance_code", "STRING"),
        bigquery.SchemaField("cible_type_code", "STRING"),
        bigquery.SchemaField("cible_reference_textuelle", "STRING"),
        bigquery.SchemaField("ingested_at", "TIMESTAMP", mode="REQUIRED"),
    ],
}
