{{ config(materialized='view') }}

select
  uid as document_uid,
  legislature,
  type_code,
  type_libelle,
  denomination_structurelle,
  provenance,
  titre_principal,
  titre_principal_court,
  dossier_ref as dossier_uid,
  date_creation,
  date_depot,
  date_publication,
  date_publication_web,
  famille_depot_code,
  famille_depot_libelle,
  famille_classe_code,
  famille_classe_libelle,
  famille_espece_code,
  famille_espece_libelle,
  type_sous_type_code,
  type_sous_type_libelle,
  num_notice,
  formule,
  adoption_conforme,
  auteur_ref,
  auteur_qualite,
  isbn,
  issn,
  dian,
  nb_page
from {{ source('raw_parleman', 'documents') }}