from google.cloud import bigquery


DEBATS_SCHEMAS: dict[str, list[bigquery.SchemaField]] = {
    "comptes_rendus": [
        bigquery.SchemaField("uid", "STRING"),
        bigquery.SchemaField("seance_ref", "STRING"),
        bigquery.SchemaField("session_ref", "STRING"),
        bigquery.SchemaField("date_seance", "STRING"),
        bigquery.SchemaField("date_seance_jour", "STRING"),
        bigquery.SchemaField("num_seance_jour", "STRING"),
        bigquery.SchemaField("num_seance", "STRING"),
        bigquery.SchemaField("type_assemblee", "STRING"),
        bigquery.SchemaField("legislature", "STRING"),
        bigquery.SchemaField("session", "STRING"),
        bigquery.SchemaField("etat", "STRING"),
        bigquery.SchemaField("diffusion", "STRING"),
        bigquery.SchemaField("version", "STRING"),
    ],
    "points_seance": [
        bigquery.SchemaField("compte_rendu_uid", "STRING"),
        bigquery.SchemaField("point_id", "STRING"),
        bigquery.SchemaField("point_type", "STRING"),
        bigquery.SchemaField("valeur_ptsodj", "STRING"),
        bigquery.SchemaField("nivpoint", "STRING"),
        bigquery.SchemaField("ordinal_prise", "STRING"),
        bigquery.SchemaField("ordre_absolu_seance", "STRING"),
        bigquery.SchemaField("code_grammaire", "STRING"),
        bigquery.SchemaField("code_style", "STRING"),
        bigquery.SchemaField("sommaire", "STRING"),
        bigquery.SchemaField("titre", "STRING"),
    ],
    "interventions": [
        bigquery.SchemaField("compte_rendu_uid", "STRING"),
        bigquery.SchemaField("point_id", "STRING"),
        bigquery.SchemaField("point_valeur_ptsodj", "STRING"),
        bigquery.SchemaField("intervention_id", "STRING"),
        bigquery.SchemaField("ordre_absolu_seance", "STRING"),
        bigquery.SchemaField("ordinal_prise", "STRING"),
        bigquery.SchemaField("code_grammaire", "STRING"),
        bigquery.SchemaField("code_style", "STRING"),
        bigquery.SchemaField("code_parole", "STRING"),
        bigquery.SchemaField("roledebat", "STRING"),
        bigquery.SchemaField("orateur_nom", "STRING"),
        bigquery.SchemaField("orateur_id", "STRING"),
        bigquery.SchemaField("orateur_qualite", "STRING"),
        bigquery.SchemaField("texte", "STRING"),
    ],
}
