from google.cloud import bigquery


DOSSIERS_LEGISLATIFS_SCHEMAS: dict[str, list[bigquery.SchemaField]] = {
    "documents": [
        bigquery.SchemaField("uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("legislature", "STRING"),
        bigquery.SchemaField("type_code", "STRING"),
        bigquery.SchemaField("type_libelle", "STRING"),
        bigquery.SchemaField("denomination_structurelle", "STRING"),
        bigquery.SchemaField("provenance", "STRING"),
        bigquery.SchemaField("titre_principal", "STRING"),
        bigquery.SchemaField("titre_principal_court", "STRING"),
        bigquery.SchemaField("dossier_ref", "STRING"),
        bigquery.SchemaField("date_creation", "TIMESTAMP"),
        bigquery.SchemaField("date_depot", "TIMESTAMP"),
        bigquery.SchemaField("date_publication", "TIMESTAMP"),
        bigquery.SchemaField("date_publication_web", "TIMESTAMP"),
        bigquery.SchemaField("famille_depot_code", "STRING"),
        bigquery.SchemaField("famille_depot_libelle", "STRING"),
        bigquery.SchemaField("famille_classe_code", "STRING"),
        bigquery.SchemaField("famille_classe_libelle", "STRING"),
        bigquery.SchemaField("famille_espece_code", "STRING"),
        bigquery.SchemaField("famille_espece_libelle", "STRING"),
        bigquery.SchemaField("type_sous_type_code", "STRING"),
        bigquery.SchemaField("type_sous_type_libelle", "STRING"),
        bigquery.SchemaField("num_notice", "STRING"),
        bigquery.SchemaField("formule", "STRING"),
        bigquery.SchemaField("adoption_conforme", "BOOLEAN"),
        bigquery.SchemaField("auteur_ref", "STRING"),
        bigquery.SchemaField("auteur_qualite", "STRING"),
        bigquery.SchemaField("isbn", "STRING"),
        bigquery.SchemaField("issn", "STRING"),
        bigquery.SchemaField("dian", "STRING"),
        bigquery.SchemaField("nb_page", "INTEGER"),
    ],
    "dossiers_parlementaires": [
        bigquery.SchemaField("uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("legislature", "STRING"),
        bigquery.SchemaField("titre_dossier", "STRING"),
        bigquery.SchemaField("titre_chemin", "STRING"),
        bigquery.SchemaField("procedure_parlementaire_code", "STRING"),
        bigquery.SchemaField("procedure_parlementaire_libelle", "STRING"),
        bigquery.SchemaField("initiateur_acteur_ref", "STRING"),
        bigquery.SchemaField("initiateur_mandat_ref", "STRING"),
        bigquery.SchemaField("initiateur_organe_ref", "STRING"),
        bigquery.SchemaField("nombre_actes_legislatifs", "INTEGER"),
    ],
    "dossier_actes_legislatifs": [
        bigquery.SchemaField("dossier_uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("acte_uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("acte_code", "STRING"),
        bigquery.SchemaField("acte_libelle_canonique", "STRING"),
        bigquery.SchemaField("acte_libelle_court", "STRING"),
        bigquery.SchemaField("organe_ref", "STRING"),
        bigquery.SchemaField("date_acte", "TIMESTAMP"),
        bigquery.SchemaField("type_acte", "STRING"),
        bigquery.SchemaField("texte_associe", "STRING"),
        bigquery.SchemaField("vote_ref", "STRING"),
    ],
}
