-- Fail only if the same mandate row is loaded more than once with identical business fields.
select
  mandat_uid,
  depute_uid,
  xsi_type,
  legislature,
  type_organe,
  organe_uid,
  date_debut,
  date_fin,
  date_publication,
  preseance,
  nomin_principale,
  code_qualite,
  lib_qualite,
  election_departement,
  election_num_departement,
  election_num_circo,
  election_cause_mandat,
  mandature_date_prise_fonction,
  mandature_cause_fin,
  mandature_premiere_election,
  mandature_place_hemicycle,
  count(*) as row_count
from {{ ref('stg_mandats') }}
group by
  mandat_uid,
  depute_uid,
  xsi_type,
  legislature,
  type_organe,
  organe_uid,
  date_debut,
  date_fin,
  date_publication,
  preseance,
  nomin_principale,
  code_qualite,
  lib_qualite,
  election_departement,
  election_num_departement,
  election_num_circo,
  election_cause_mandat,
  mandature_date_prise_fonction,
  mandature_cause_fin,
  mandature_premiere_election,
  mandature_place_hemicycle
having count(*) > 1
