from google.cloud import bigquery


SCRUTINS_SCHEMAS: dict[str, list[bigquery.SchemaField]] = {
    "scrutins": [
        bigquery.SchemaField("uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("numero", "STRING"),
        bigquery.SchemaField("legislature", "STRING"),
        bigquery.SchemaField("organe_ref", "STRING"),
        bigquery.SchemaField("session_ref", "STRING"),
        bigquery.SchemaField("seance_ref", "STRING"),
        bigquery.SchemaField("date_scrutin", "DATE"),
        bigquery.SchemaField("quantieme_jour_seance", "INTEGER"),
        bigquery.SchemaField("type_vote_code", "STRING"),
        bigquery.SchemaField("type_vote_libelle", "STRING"),
        bigquery.SchemaField("type_majorite", "STRING"),
        bigquery.SchemaField("sort_code", "STRING"),
        bigquery.SchemaField("sort_libelle", "STRING"),
        bigquery.SchemaField("titre", "STRING"),
        bigquery.SchemaField("demandeur_texte", "STRING"),
        bigquery.SchemaField("demandeur_reference_legislative", "STRING"),
        bigquery.SchemaField("objet_libelle", "STRING"),
        bigquery.SchemaField("objet_dossier_legislatif", "STRING"),
        bigquery.SchemaField("objet_reference_legislative", "STRING"),
        bigquery.SchemaField("mode_publication_votes", "STRING"),
        bigquery.SchemaField("lieu_vote", "STRING"),
        bigquery.SchemaField("synthese_nombre_votants", "INTEGER"),
        bigquery.SchemaField("synthese_suffrages_exprimes", "INTEGER"),
        bigquery.SchemaField("synthese_nbr_suffrages_requis", "INTEGER"),
        bigquery.SchemaField("synthese_annonce", "STRING"),
        bigquery.SchemaField("synthese_non_votants", "INTEGER"),
        bigquery.SchemaField("synthese_pour", "INTEGER"),
        bigquery.SchemaField("synthese_contre", "INTEGER"),
        bigquery.SchemaField("synthese_abstentions", "INTEGER"),
        bigquery.SchemaField("synthese_non_votants_volontaires", "INTEGER"),
    ],
    "scrutin_groupes_votes": [
        bigquery.SchemaField("scrutin_uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("organe_ref_assemblee", "STRING"),
        bigquery.SchemaField("groupe_organe_ref", "STRING"),
        bigquery.SchemaField("nombre_membres_groupe", "INTEGER"),
        bigquery.SchemaField("position_majoritaire", "STRING"),
        bigquery.SchemaField("non_votants", "INTEGER"),
        bigquery.SchemaField("pour", "INTEGER"),
        bigquery.SchemaField("contre", "INTEGER"),
        bigquery.SchemaField("abstentions", "INTEGER"),
        bigquery.SchemaField("non_votants_volontaires", "INTEGER"),
    ],
    "scrutin_votes_individuels": [
        bigquery.SchemaField("scrutin_uid", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("groupe_organe_ref", "STRING"),
        bigquery.SchemaField("position_vote", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("acteur_ref", "STRING"),
        bigquery.SchemaField("mandat_ref", "STRING"),
        bigquery.SchemaField("par_delegation", "BOOLEAN"),
        bigquery.SchemaField("num_place", "STRING"),
        bigquery.SchemaField("cause_position_vote", "STRING"),
        bigquery.SchemaField("source", "STRING", mode="REQUIRED"),
    ],
}
